name: reloader
description: A library to reload dart VM if code was changed. Tool reloads your code when source was changed.
version: 0.1.2

author: 0xff00ff <0xff00ff@gmail.com>
homepage: "https://github.com/0xff00ff/reloader"

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  vm_service_lib: ^0.3.5
  watcher: ^0.9.7
  path: ^1.6.2
executables:
  reloader: